version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: habittracker-backend
    env_file:
      - ./Backend/.env
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: habittracker-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=HabitTrackerDB
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:
